### PR TITLE
Cxc 386 sub category tabs not fixed sticky

### PR DESCRIPTION
**Pull request by Annacc211018**
Subnavigation is now sticky again on mobile, as well as the category-name, the search bar, filter icon and closing icon.

It's deployed here so please check on a mobile phone. :)
https://cxc-386.netlify.app/

### CODE REVIEW

**Comment by AntoinouM** [comment]
Very nice! I did struggle with this. The only thing would be that there is space between the menu and the sides :
Screenshot 2024-05-17 at 12 03 02

**Comment by hollaa** [comment]
For me (iphone, safari) the color of the font in bottom nav is blue now, Im not sure why because I dont see it like that when I open it on desktop in mobile format. Also It seems like the div of the search would need a background color. 
IMG_1566

**Comment by Vanessi-K** [comment]
Something that I also found on other branches, but i think would fit into here is that on Chrome you have two search-bars next to each other. Where the inner one does not do anything.

image

**Comment by Annacc211018** [comment]
@AntoinouM  @Vanessi-K @hollaa the mentioned issues should all be fixed now:

- removed the padding of the catalog overlay by passing the padding as a prop when it's different for an overlay
- set the z-index higher for the search bar and category title, so the assets should be behind them when scrolling at all times (this was iPhone specific)
- set the color of the icons in the subnavs of the catalog so they are always black when not selected (was iPhone specific)
- removed the second scroll bar on browser resize (this was only happening on desktop when the window was resized as far as I could replicate)

please check again, if possible.

Thanks!

**Pull request merged**
