### PR TITLE
CXC-416: can't select category after closing it

### PR DESCRIPTION
**Pull request by Vanessi-K**
Now you are able to select a category right after each other.

Because I was confused with some of the logic I simplified it a bit and also removed a repeated call to the API.
⚠️ Please carefully check the complete catalog behavior: category, sub-category, search, filter. if everything is still working well. On mobile and on desktop.

### CODE REVIEW

**Comment by Vanessi-K** [comment]
> Now you are able to select a category right after each other.
> 
> Because I was confused with some of the logic I simplified it a bit and also removed a repeated call to the API. ⚠️ Please carefully check the complete catalog behavior: category, sub-category, search, filter. if everything is still working well. On mobile as well as on desktop.

**Comment by Vanessi-K** [comment]
>     * Bottom nav is scroll able on X
>       https://github.com/comixcraft/Editor/assets/92710938/16077da5-aabc-40aa-aa84-f31079fcc427

The sub-categories being horizontally scroll able, if they don't fit is intended behaviour, as it behaves this way also on mobile.

**Comment by AntoinouM** [comment]
I tested on iPhone on Chrome, Safari and Moz. It works very well, can reopen a closed category, sub-category and filters have the same behavior than before.

One little thing: On all 3 browser, it seems that when I open a category, the assets are displayed and then slightly scrolled up 

https://github.com/comixcraft/Editor/assets/92710938/48e6ffe3-0b1d-4f38-a7d8-ef3d3a6fd94b

I think this PR should be merged, and this slight scroll be created as a new bug unless you want to have a look at it.

**Comment by AntoinouM** [comment]
Good work!

**Pull request merged**
