### PR TITLE
CXC-392-Category-Styling

### PR DESCRIPTION
**Pull request by moonjuko**
Subcategory and Category names should be consistent with FIGMA design.
Added “All Assets“ as the first thing in the navigation
Removed the white shadow to the right of the subcategories menu that needs to be removed.
Subcategories are centered as they are in the design.
Please review.

### CODE REVIEW

**Review by Vanessi-K — CHANGES_REQUESTED** [review]
1. The sub-categories in for "Annotation Elements" are cut-off. (It can not be scrolled further right) -> Firefox
image

2. I am not sure that it is good that now there also is no shadow on the right side of the sub-category-menu. For me this looks a bit cut off. What do you think?

2. Something in the spacing of the sub-category-menu seems of, since in the design the height is 80px where now the height is over 100px. Which especially on smaller screens is quite large.

**Comment by Vanessi-K** [comment]
Since no Netlify link was provided I did only test on desktop.

**Comment by moonjuko** [comment]
> 1. The sub-categories in for "Annotation Elements" are cut-off. (It can not be scrolled further right) -> Firefox
>    image
> 2. I am not sure that it is good that now there also is no shadow on the right side of the sub-category-menu. For me this looks a bit cut off. What do you think?
> 3. Something in the spacing of the sub-category-menu seems of, since in the design the height is 80px where now the height is over 100px. Which especially on smaller screens is quite large.

Hi Vanessa! Yes, there was some styling errors there, could you please review them again? In regards of the shadow, I found the best way , was to also create a shadow on the catalogContainer div that, otherwise it looked pretty weird with the side shadow only on the sub navigation.

**Comment by moonjuko** [comment]
> Since no Netlify link was provided I did only test on desktop.

https://cxc-392-category-styling--cxc-392-category-styling.netlify.app/

**Comment by Vanessi-K** [comment]
When the window is resized the scroling is still glitched out for me:
image

**Comment by Vanessi-K** [comment]
I really like the shadows now.

**Review by Vanessi-K — APPROVED** [review]

**Pull request merged**
