### PR TITLE
CXC-Top-navigation-is-inconsistent

### PR DESCRIPTION
**Pull request by hollaa**
The styling of navigation should be consistent now across screens in all devices
 deleted top-nav-lg class from _navigation.scss because it is not necessary anymore
- now we are using the same styling for mobile and desktop
- had to "display:block" for editor.vue otherwise the height of the navigation menu was not adjustable
- back button in export.vue is a button now to ensure consistent styling

### CODE REVIEW

**Review by Vanessi-K — CHANGES_REQUESTED** [review]
The go back buttons in the navigation are slightly more right than the "Layers"-text or he logo (don't think though that we need to waste a lot of time on this).

With your recent changes the editor page now has a scroll-bar that was not there before. And it does not do much. This should be removed again.

The two buttons on the export page are not centered anymore in mobile-view (is the case on dev and production). This needs to be adjusted again.

Your branch:
image

Production:
image

**Comment by Vanessi-K** [comment]
I could not yet test on a real phone, since the provided Netlify link seems to be broken.

**Comment by hollaa** [comment]
@Vanessi-K I have adjusted the changes

**Comment by Vanessi-K** [comment]
Generally everything ok from my side now, but there is a merge conflict that needs to be resolved.

**Review by Vanessi-K — APPROVED** [review]

**Pull request merged**
