### PR TITLE
Cxc 420 bottom nav not visible scrollable

### PR DESCRIPTION
**Pull request by Annacc211018**
Bug/Improvement: Not clear if the bottom nav is scrollable because of the cuttoff.
I added an overlay effect to the subnavigation for mobile devices to make it more clear.

Please check css classes and naming convention as I am still a bit unsure about them.

### CODE REVIEW

**Comment by AntoinouM** [comment]
I think that this solution is not really straight forward. Adding div_s_ to the code is adding some complexity and making the source code harder to read and maintain later on.

I think it would have been easier to use box-shadow that could be applied straight in the code.
[here is an example and a generator](https://devdevout.com/css/css-inner-shadow)

If you don't want to refactor here are some observations:

- the sub-category could also be scrollable and I am not sure the shadows would show with this code (did not on my phone when I tried).
- the shadow is more like a mask as the cut-off is really hard:
Screenshot 2024-06-01 at 14 45 40

**Comment by Vanessi-K** [comment]
On a small browser-window it looks a bit weird (in Firefox): 
image

**Comment by AntoinouM** [comment]
Was this after resizing?

**Comment by Vanessi-K** [comment]
On the phone it looks very nice. The only thing is that the scroll behavior is a bit weird, since for it to scroll, I can not touch the shadow. This also makes it especially annoying to click the most right element. Since you can only really click it, when you scrolled completely to the right.

**Comment by Vanessi-K** [comment]
> Was this after resizing?

Yes.
If I open it already in a small size I have this weird gap: 
image

**Comment by AntoinouM** [comment]
Ok, I did not handle resizing. Does this gap only happen in firefox?

**Review by Vanessi-K — CHANGES_REQUESTED** [review]
In general I also thing that the placement of the logic is a bit odd. Why is this in `editor.vue` instead of `CatalogNavigation.vue`.

**Comment by Vanessi-K** [comment]
> Ok, I did not handle resizing. Does this gap only happen in firefox?

It is also happening in Chrome

**Comment by AntoinouM** [comment]
> In general I also thing that the placement of the logic is a bit odd. Why is this in `editor.vue` instead of `CatalogNavigation.vue`.

It is in editor because the scrollable container is a div of editor and not in CatalogNavigation. So most of the scroll logic needs to be there. I would also prefer for it to be elsewhere but I did not want to refactor all the code.

**Review by AntoinouM — APPROVED** [review]

**Review by Vanessi-K — APPROVED** [review]

**Pull request merged**
